import { Product } from "@/types";

export const products: Product[] = [
  {
    id: "1",
    name: "YZY GAP HOODIE",
    slug: "yzy-gap-hoodie",
    description: "Double layer cotton hoodie. Vintage wash processing.",
    price: 160,
    category_id: "buzos",
    brand: "YEEZY",
    stock: 100,
    images: ["https://images.stockx.com/images/Yeezy-Gap-Dove-Shrunken-Hoodie-Black.jpg?fit=fill&amp;bg=FFFFFF&amp;w=576&amp;h=384&amp;q=57&amp;dpr=2&amp;trim=color&amp;updated_at=1653666222"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black"],
    created_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "SUPREME BOX LOGO",
    slug: "supreme-box-logo",
    description: "Heavyweight cotton crossgrain fleece with embroidered logo.",
    price: 250,
    category_id: "buzos",
    brand: "SUPREME",
    stock: 50,
    images: ["https://images.stockx.com/images/Supreme-Box-Logo-Hooded-Sweatshirt-FW25-Realtree-AP-Camo-Product.jpg?fit=fill&amp;bg=FFFFFF&amp;w=576&amp;h=384&amp;q=57&amp;dpr=2&amp;trim=color&amp;updated_at=1764861839"],
    sizes: ["M", "L", "XL"],
    colors: ["Black", "Grey"],
    created_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "NIKE NOCTA PUFFER",
    slug: "nike-nocta-puffer",
    description: "Water-repellent fabric with down insulation.",
    price: 400,
    category_id: "camperas",
    brand: "NIKE",
    stock: 20,
    images: ["https://images.stockx.com/images/Nike-x-NOCTA-Sunset-Puffer-Jacket-Mica-Green-v2.jpg?fit=fill&amp;bg=FFFFFF&amp;w=576&amp;h=384&amp;q=57&amp;dpr=2&amp;trim=color&amp;updated_at=1737644219 "],
    sizes: ["L", "XL"],
    colors: ["Black"],
    created_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "CORTEIZ CARGO",
    slug: "corteiz-cargo",
    description: "Guerillaz cargo pants with multiple pockets.",
    price: 180,
    category_id: "pantalones",
    brand: "CORTEIZ",
    stock: 30,
    images: ["https://images.stockx.com/images/Corteiz-Alcatraz-Cargo-Shorts-Black.jpg?fit=fill&amp;bg=FFFFFF&amp;w=576&amp;h=384&amp;q=57&amp;dpr=2&amp;trim=color&amp;updated_at=1688397970"],
    sizes: ["30", "32", "34"],
    colors: ["Black"],
    created_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "BAPE SHARK HOODIE",
    slug: "bape-shark-hoodie",
    description: "Full zip hoodie with shark motif.",
    price: 350,
    category_id: "buzos",
    brand: "BAPE",
    stock: 15,
    images: ["https://images.stockx.com/images/BAPE-Color-Camo-Shark-Full-Zip-Hoodie-Purple-ProductX.jpg?fit=fill&amp;bg=FFFFFF&amp;w=576&amp;h=384&amp;q=57&amp;dpr=2&amp;trim=color&amp;updated_at=1744142786"],
    sizes: ["M", "L", "XL"],
    colors: ["Camo"],
    created_at: new Date().toISOString(),
  },
  {
    id: "6",
    name: "HELLSTAR TEE",
    slug: "hellstar-tee",
    description: "Vintage wash graphic tee.",
    price: 120,
    category_id: "remeras",
    brand: "HELLSTAR",
    stock: 40,
    images: ["https://images.stockx.com/images/Hellstar-Classic-T-Shirt-Black-Product.jpg?fit=fill&amp;bg=FFFFFF&amp;w=576&amp;h=384&amp;q=57&amp;dpr=2&amp;trim=color&amp;updated_at=1755622308"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black"],
    created_at: new Date().toISOString(),
  },
];
